### ISSUE TITLE
Is pilot token still needed? How to activate plunging with out Pilot token? 

### ISSUE THREAD

**Issue by TeroKeso** [traefik/plugin-simplecache#20]
"Say goodbye to Traefik Pilot As of October 4th, 2022, and as [previously announced](https://traefik.io/blog/announcing-traefik-proxy-2-8/), Traefik Pilot is no longer available."

"
[pilot]
  token="xxx"
"

**Comment by ldez** [comment]
Hello,

Pilot is now off, the Pilot token is now useless to access plugins.
The plugins are now a standalone service: https://plugins.traefik.io/plugins

**Comment by TeroKeso** [comment]
Will you update your documentation?  :D

<img width="648" alt="image" src="https://user-images.githubusercontent.com/29271631/194017115-f555031b-a8be-46a7-85bc-0684364c5a8b.png">

**Comment by ldez** [comment]
fixed 0114d8390b5e0727e3c156b4dffe6899acd2190f
